      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"
          channelId: "live"
          projectId: "nifty-quanta-475212-v3"
          token: "${{ secrets.FIREBASE_CI_TOKEN }}"
